routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function(){

    // Admin profile
    Route::get('profile', 'AdminController@profile');
    Route::get('profile/edit', 'AdminController@profileEdit');
    Route::patch('profile/edit', 'AdminController@profileUpdate');
    Route::patch('profile/edit-password', 'AdminController@profilePasswordUpdate');

    Route::group(['middleware' => 'adminOnly'], function(){
        Route::resource('category', 'CategoryController');
        Route::resource('user', 'UserController');
        Route::resource('video', 'VideoController');
        Route::resource('plan', 'SubscriptionPlanController');
        Route::resource('transactions', 'TransactionController');
        Route::get('series/reorder', 'SeriesController@reorder');
        Route::patch('series/reorder', 'SeriesController@reorderSave');
        Route::resource('series', 'SeriesController');
        Route::resource('admin', 'AdminController');
        Route::get('transactions/invoice/{id}', 'TransactionController@invoice');

        // Requests
        Route::get('requests', 'RequestsController@index');
        Route::post('requests/{id}/grant', 'RequestsController@grantAccess');
        Route::post('requests/destroy/{id}', 'RequestsController@destroy');
        Route::post('requests/back/{id}', 'RequestsController@backOfficeAddSub');
        
        // reports
        Route::get('reports', 'ReportController@index');
        Route::post('reports', 'ReportController@index');

        // export
        Route::post('export/requests', 'ReportController@exportRequests');
        Route::post('export/users', 'ReportController@exportUsers');

        // Run execution of charge
        Route::get('run-charge',function() {
            Artisan::call("charge");
        });

        // Revert execution of charge
        Route::get('revert-charge',function() {
            Artisan::call("revertcharge");
        });
    });
    
});

Route::get('/thumbnail-reponse/{id}', 'MiscController@thumbnail');
Route::get('remove-unverified-user', 'UserController@removeUnverified');

app/User.php
<?php

namespace App;

use Laravel\Passport\HasApiTokens;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use HasApiTokens, Notifiable;

    use SoftDeletes;
    
    public $table = 'users';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'middle_name', 'last_name', 'user_name',  'email', 'password', 'activation_token', 'status'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token'
    ];


    public static function boot()
    {
        parent::boot();    
        // cause a delete of a product to cascade to children so they are also deleted
        static::deleted(function($user)
        {
            $user->transactions()->delete();
            $user->userSubscription()->delete();
        });
    }

    /**
     * Mutator
     * Full name
     */
    public function getFullNameAttribute() {
            return "{$this->first_name} {$this->last_name}";
    }

    /**
     * Relationships
     */

    public function transactions() {
        return $this->hasMany(\App\Models\Transaction::class, 'user_id');
    }

    public function latestTransaction() {
        return $this->hasMany(\App\Models\Transaction::class, 'user_id')->latest();
    }

    public function plan() {
        return $this->hasOne(\App\Models\Subscription::class, 'user_id')->whereIn('status', ['ACTIVE'])->latest();
    }

    public function subscription() {
        return $this->hasOne(\App\Models\Subscription::class, 'user_id')->with('plan')->whereIn('status', ['ACTIVE', 'LAPSED'])->latest();
    }

    public function userSubscription() {
        return $this->hasOne(\App\Models\Subscription::class, 'user_id');
    }

}

app/Http/Controllers/API/UserController.php
<?php
namespace App\Http\Controllers\API;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use App\Http\Controllers\Controller;
use App\Notifications\VerifyEmail;
use App\User;

use Validator;
class UserController extends Controller
{
    public $successStatus = 200;

    /**
     * login api
     *
     * @return \Illuminate\Http\Response
     */
    public function login(){

        $checkUser = User::with(['plan', 'subscription'])->where('email', request('email'))->first();

        if ($checkUser) {
            if (Hash::check(request('password'), $checkUser->password)) {
                if ($checkUser->status === 'EMAIL_VERIFICATION') {
                    return response()->json([
                        'message'=>'Email not yet verified',
                        'error'=>'false'
                    ], 401);
                }
                $user = $checkUser;
                $success['token'] =  $user->createToken('VideoStreaming')->accessToken;
                $success['user'] = $user;

                return response()->json( $success, $this->successStatus);
            }
        }
        return response()->json([
            'message' => 'Username or Password is invalid',
            'error' => true
        ], 401);
    }

    /**
     * login with activation token
     *
     * @return \Illuminate\Http\Response
     */
    public function loginWithAuthToken(){

        $checkUser = User::with(['plan', 'subscription'])->where('activation_token', request('token'))->first();

        if ($checkUser) {
            if ($checkUser->status === 'EMAIL_VERIFICATION') {
                return response()->json([
                    'message'=>'Email not yet verified',
                    'error'=>'false'
                ], 401);
            }
            $user = $checkUser;
            $success['token'] =  $user->createToken('VideoStreaming')->accessToken;
            $success['user'] = $user;

            return response()->json( $success, $this->successStatus);
        }
        return response()->json([
            'message' => 'Auth token is invalid',
            'error' => true
        ], 401);
    }

    /**
     * Register api
     *
     * @return \Illuminate\Http\Response
     */
    public function register(Request $request)
    {
        $response = new \stdClass;
        $response->message = 'User created and waiting for email verification';
        $response->error = false;

        $messages = [
            'unique' => 'The :attribute has already been taken.',
            'email' => 'The :attribute has already been taken.'
        ];

        
        $validator = Validator::make($request->all(), [
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required',
        ], $messages);

        if ($validator->fails()) {
            $response->message = $validator->errors();
            return response()->json($response, 400);
        }

        $input = $request->all();
        $input['password'] = Hash::make($input['password']);
        $input['activation_token'] = Str::random(60);
        $user = User::create($input);

        if (!$user) {
            if (!$user) {
                $user->message = $user;
            }

            $user->error = true;
        } else {
             $user->notify(
                new VerifyEmail($user->activation_token)
            );
        }
        return response()->json($user);

    }

    /**
     * Forgot password
     */

    public function verifyEmail() {
        $response = [
            'message' => '',
            'error' => true,
            'code' => 400
        ];

        $user = User::where('activation_token', request('token'))->first();

        if ($user) {

            switch ($user->status) {
                case "ACTIVE":
                    $response['message'] = 'Email is already verified';
                break;
                case "DELETE":
                    $response['message'] = 'Connected email has been deleted';
                break;
                case "SUSPEND":
                    $response['message'] = 'Connected email is suspended';
                break;
                case "EMAIL_VERIFICATION":
                    $user->status = 'active';
                    $user->save();

                    $response['message'] = "Email has been verified";
                    $response['token'] = $user->activation_token;
                    $response['error'] = false;
                    $response['code'] = 200;
                break;
            }

        } else {
            $response['message'] = "Error occured. Please contact support.";
            $response['error'] = true;
        }

        return response()->json($response, $response['code']);

    }


    /**
     * details api
     *
     * @return \Illuminate\Http\Response
     */
    public function details(Request $request)
    {
        $user = User::with(['subscription'])->find($request->header('x-user-id'));
        if ($user) {
            return response()->json([ 'data' => $user], $this->successStatus);
        }
        return response()->json([ 'message' => 'User not found', 'error' => true], 400);
    }

    /**
     * Check user if Authenticated
     *
     * @return \Illuminate\Http\Response
     */
    public function checkUser(Request $request)
    {
        $user = User::with(['plan', 'subscription'])->find($request->header('x-user-id'));
        if ($user) {
            return response()->json(['authenticated' => true, 'user' => $user, 'token'=>$user->createToken('VideoStreaming')->accessToken], $this->successStatus);

        }
        return response()->json(['authenticated' => true], $this->successStatus);
    }

    /**
     * Update user
     */
    public function update($id, Request $request) {
        $response = new \stdClass;
        $response->message = '';
        $response->error = false;

        $messages = [
            'min' => 'The :attribute must be minimum of :min alphanumeric characters',
            'unique' => 'The :attribute has already been taken.'
        ];

        $user = User::find($id);
        if ($user) {
            $validator = Validator::make($request->all(), [
                // 'user_name' => 'required|string|alpha_num|min:8|max:255|unique:users,user_name,'.$id,
            ], $messages);
    
            if ($validator->fails()) {
                $response->message = $validator->errors();
                return response()->json($response, 400);
            }

            $user->fill($request->all());

            $user->save();

            return response()->json([ 'data' => $user], $this->successStatus);
        }
        return response()->json([ 'message' => 'User not found', 'error' => true], 400);
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\User;
use Illuminate\Http\Request;
use App\Models\SubscriptionPlan;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\View\View
     */
    public function index(Request $request)
    {
        $keyword = $request->get('table_search');
        $perPage = 25;

        if (!empty($keyword)) {
            $user = User::where('first_name', 'like', '%' . $keyword . '%')
            ->orWhere('user_name', 'like', '%' . $keyword . '%')
            ->orWhere('middle_name', 'like', '%' . $keyword . '%')
            ->orWhere('last_name', 'like', '%' . $keyword . '%')
            ->orWhere('email', 'like', '%' . $keyword . '%')
            ->latest()->paginate($perPage);
        } else {
            $user = User::latest()->paginate($perPage);
        }

        return view('user.index', compact('user'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        return view('user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {

        $requestData = $request->all();
        
        $validator = Validator::make($requestData, [
            // 'first_name' => 'required|string|max:255',
            // 'last_name' => 'required|string|max:255',
            'user_name' => 'nullable|string|max:255|unique:users',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:6|confirmed',
        ]);

        if ($validator->fails()) {
            return redirect('user/create')
            ->withInput()
            ->withErrors($validator);
        }

        $requestData['password'] = Hash::make($requestData['password']);
        $requestData['activation_token'] = Str::random(60);

        User::create($requestData);

        return redirect('user')->with('flash_message', 'User added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\View\View
     */
    public function show($id)
    {
        $user = User::findOrFail($id);
        $subscriptions = SubscriptionPlan::where('status', 'ENABLED')->get();

        return view('user.show', compact('user', 'subscriptions'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\View\View
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);

        return view('user.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param  int  $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(Request $request, $id)
    {

        $requestData = $request->all();

        $validator = Validator::make($requestData, [
            // 'first_name' => 'required|string|max:255',
            // 'last_name' => 'required|string|max:255',
            'user_name' => 'nullable|string|max:255|unique:users,user_name,'.$id,
            'email' => 'required|string|email|max:255|unique:users,email,'.$id,
        ]);

        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput($request->all());
        }

        $user = User::findOrFail($id);
        $user->update($requestData);

        return redirect('user')->with('flash_message', 'User details updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy($id)
    {
        User::destroy($id);
        
        return redirect('user')->with('flash_message', 'User deleted!');
    }

    public function removeUnverified()
    {
        $data = User::where('status','EMAIL_VERIFICATION')
        ->where('created_at', '<', \Carbon\Carbon::now()->subWeek())
        ->orderBy('created_at','DESC')
        ->forceDelete();
    }
}

resources/views/user/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="content-wrapper">
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Create New User</h1>
                    </div>
                </div> 
            </div>
        </div>
        <section class="content">
            <div class="row px-2">
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-header">Create New User</div>
                        <div class="card-body">
                            <a href="{{ url('/user') }}" title="Back"><button class="btn btn-warning btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a>
                            <br />
                            <br />

                            @if ($errors->any())
                                <ul class="alert alert-danger">
                                    @foreach ($errors->all() as $error)
                                        <li class="ml-2">{{ $error }}</li>
                                    @endforeach
                                </ul>
                            @endif

                            <form method="POST" action="{{ url('/user') }}" accept-charset="UTF-8" class="form-horizontal" enctype="multipart/form-data">
                                {{ csrf_field() }}

                                @include ('user.form', ['formMode' => 'create'])

                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

@endsection

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="content-wrapper">
            <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                <h1 class="m-0 text-dark">Edit User</h1>
                </div><!-- /.col -->
            </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>

        <section class="content">
            <div class="row px-2">
    
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-header">Edit User</div>
                        <div class="card-body">
                            <a href="{{ url('/user') }}" title="Back"><button class="btn btn-warning btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a>
                            <br />
                            <br />
    
                            @if ($errors->any())
                                <ul class="alert alert-danger">
                                    @foreach ($errors->all() as $error)
                                        <li class="ml-2">{{ $error }}</li>
                                    @endforeach
                                </ul>
                            @endif
    
                            <form method="POST" action="{{ url('/user/' . $user->id) }}" accept-charset="UTF-8" class="form-horizontal" enctype="multipart/form-data">
                                {{ method_field('PATCH') }}
                                {{ csrf_field() }}
    
                                @include ('user.form', ['formMode' => 'edit'])
    
                            </form>
    
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/user/form.blade.php
<div class="form-group {{ $errors->has('user_name') ? 'has-error' : ''}}">
    <label for="user_name" class="control-label">{{ 'Username' }}</label>
    <input class="form-control" name="user_name" type="text" id="user_name" value="{{ isset($user->user_name) ? $user->user_name : old('user_name')}}" >
    {!! $errors->first('user_name', '<p class="text-danger help-block">:message</p>') !!}
</div>
<div class="form-group {{ $errors->has('email') ? 'has-error' : ''}}">
    <label for="email" class="control-label">{{ 'Email' }}</label>
    <input class="form-control" name="email" type="text" id="email" value="{{ isset($user->email) ? $user->email : old('email')}}" autocomplete="off">
    {!! $errors->first('email', '<p class="text-danger help-block">:message</p>') !!}
</div>
<div class="form-group {{ $errors->has('first_name') ? 'has-error' : ''}}">
    <label for="first_name" class="control-label">{{ 'First Name' }}</label>
    <input class="form-control" name="first_name" type="text" id="first_name" value="{{ isset($user->first_name) ? $user->first_name : old('first_name') }}" >
    {!! $errors->first('first_name', '<p class="text-danger help-block">:message</p>') !!}
</div>
<div class="form-group {{ $errors->has('middle_name') ? 'has-error' : ''}}">
    <label for="middle_name" class="control-label">{{ 'Middle Name' }}</label>
    <input class="form-control" name="middle_name" type="text" id="middle_name" value="{{ isset($user->middle_name) ? $user->middle_name : old('middle_name')}}" >
    {!! $errors->first('middle_name', '<p class="text-danger help-block">:message</p>') !!}
</div>
<div class="form-group {{ $errors->has('last_name') ? 'has-error' : ''}}">
    <label for="last_name" class="control-label">{{ 'Last Name' }}</label>
    <input class="form-control" name="last_name" type="text" id="last_name" value="{{ isset($user->last_name) ? $user->last_name : old('last_name')}}" >
    {!! $errors->first('last_name', '<p class="text-danger help-block">:message</p>') !!}
</div>

@if (!isset($user->password))
    <div class="form-group {{ $errors->has('password') ? 'has-error' : ''}}">
        <label for="password" class="control-label">{{ 'Password' }}</label>
        <input class="form-control" name="password" type="password" id="password" value="{{ isset($user->password) ? $user->password : ''}}" autocomplete="off">
        {!! $errors->first('password', '<p class="text-danger help-block">:message</p>') !!}
    </div>
    <div class="form-group">
        <label for="c_password" class="control-label">{{ 'Confirm Password' }}</label>
        <input class="form-control" name="password_confirmation" type="password" id="c_password"  autocomplete="off">
    </div>
@endif

<div class="form-group {{ $errors->has('status') ? 'has-error' : ''}}">
    <label for="status" class="control-label">{{ 'Status' }}</label>
    <select class="form-control" name="status" id="status">
        @if (isset($user->status))
            <option {{ $user->status == 'ACTIVE' ? 'selected': ''}} value="ACTIVE">ACTIVE</option>
            <option {{ $user->status == 'DELETED' ? 'selected': ''}} value="DELETED">DELETED</option>
            <option {{ $user->status == 'SUSPEND' ? 'selected': ''}} value="SUSPEND">SUSPEND</option>
        @else
            <option value="ACTIVE">ACTIVE</option>
            <option value="DELETED">DELETED</option>
            <option value="SUSPEND">SUSPEND</option>
        @endif
        </select>
    {!! $errors->first('status', '<p class="text-danger help-block">:message</p>') !!}
</div>

<!-- <div class="form-group {{ $errors->has('password') ? 'has-error' : ''}}">
    <label for="password" class="control-label">{{ 'Password' }}</label>
    <input class="form-control" name="password" type="text" id="password" value="{{ isset($user->password) ? $user->password : ''}}" >
    {!! $errors->first('password', '<p class="text-danger help-block">:message</p>') !!}
</div> -->


<div class="form-group">
    <input class="btn btn-primary" type="submit" value="{{ $formMode === 'edit' ? 'Update' : 'Create' }}">
</div>

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')
  
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Users</h1>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>


      <section class="content">
        <div class="row px-2">
          @if(Session::has('flash_message'))
            <div class="col-lg-12">
              <div class="alert alert-success px-2">
                  <span class="glyphicon glyphicon-ok"></span><em> {!! session('flash_message') !!}</em>
              </div>
            </div>
          @endif
            <div class="col-12">
              <div class="card">
                <div class="card-header">
                  {{-- <h3 class="card-title">User List</h3> --}}
                  <a href="{{ url('/user/create') }}" title="Back"><button class="btn btn-primary btn-sm mt-n2 mb-n1"><i class="fa fa-plus" aria-hidden="true"></i> Add New</button></a>
                  <div class="card-tools">
                    <form method="GET" action="{{ url('/user') }}">
                        <div class="input-group input-group-sm" style="width: 150px;">
                          <input type="text" name="table_search" class="form-control float-right" placeholder="Search">
                          <div class="input-group-append">
                            <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                          </div>
                        </div>
                    </form>
                  </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body table-responsive p-0">
                  <table class="table table-hover text-nowrap">
                    <thead>
                      <tr>
                        <th>Name</th><th>Email</th><th>Status</th><th width="100">Actions</th>
                      </tr>
                    </thead>
                    <tbody>
                        @if(count($user) == 0)
                              <tr><td colspan="100%"><div class="alert alert-danger">No data found</div></td></tr>
                        @else
                            @foreach($user as $item)
                                <tr>
                                  <td>{{ $item->full_name }}</td>
                                  <td>{{ $item->email }}</td>
                                  

                                  <td>
                                    @if ($item->status === 'ACTIVE')
                                    <span class="badge bg-primary">{{ $item->status }}</span>
                                    @elseif ($item->status === 'DELETED')
                                    <span class="badge bg-danger">{{ $item->status }}</span>
                                    @elseif ($item->status === 'SUSPEND')
                                    <span class="badge bg-warning">{{ $item->status }}</span>
                                    @elseif ($item->status === 'EMAIL_VERIFICATION')
                                    <span class="badge bg-success">{{ $item->status }}</span>
                                    @endif
                                  
                                  </td>
                                    <td>
                                        <a href="{{ url('/user/' . $item->id) }}" title="View user"><button class="btn btn-info btn-sm"><i class="fa fa-eye" aria-hidden="true"></i> View</button></a>
                                        <a href="{{ url('/user/' . $item->id . '/edit') }}" title="Edit user"><button class="btn btn-primary btn-sm"><i class="fa fa-edit" aria-hidden="true"></i> Edit</button></a>

                                        <form method="POST" action="{{ url('/user' . '/' . $item->id) }}" accept-charset="UTF-8" style="display:inline">
                                            {{ method_field('DELETE') }}
                                            {{ csrf_field() }}
                                            <button type="submit" class="btn btn-danger btn-sm" title="Delete user" onclick="return confirm(&quot;Confirm delete?&quot;)"><i class="fa fa-trash" aria-hidden="true"></i> Delete</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        @endif
                    </tbody>
                  </table>
                  @if(count($user) > 0)
                    <div class="pagination-wrapper px-3"> {!! $user->appends(['search' => Request::get('search')])->render() !!} </div>
                  @endif
                </div>
                <!-- /.card-body -->
              </div>
              <!-- /.card -->
            </div>
          </div>
      </section>
    </div>
    <!-- /.content-header -->

@endsection